FROM python:3.11.10
WORKDIR /app
COPY . /app
RUN apt update && pip install --upgrade pip
RUN apt update && apt install -y locales
RUN pip install --no-cache-dir -r requirements.txt
EXPOSE 5001
CMD ["python", "app.py"]
